export const LANG_BR_NAME = 'br';

export const LANG_BR_TRANS = {
  'Map':'Mapa',
  'Faves':'Favoritos',
  'Search':'Pesquisa',
  'Home':'Casa',
  'To Rent':'Alugar',
  'For Sale':'À venda',
  'Nestoria Rank':'Rank Nestoria',
  'Price (low to high)':'Preço (baixo para alto)',
  'Price (high to low)':'Preço (alto a baixo)',
  'Beds (fewer first)':'Camas (menos primeiro)',
  'Beds (more first)':'Camas (mais primeiro)',
  'Date (older first)':'Data (mais antigo primeiro)',
  'Date (newer first)':'Data (mais recente primeiro)',
  'Bedrooms':'Quartos de dormir',
  'Price':'Preço',
  'Property type':'Tipo de Propriedade',
  'all':'todos',
  'flat':'plano',
  'house':'casa',
  'Bathrooms':'Banheiros',
  'Filters':'Filtros',
  '£':'R$',
};
