export const LANG_UK_NAME = 'uk';

export const LANG_UK_TRANS = {
  'Map':'',
  'Faves':'',
  'Search':'',
  'Home':'',
  'To Rent':'',
  'For Sale':'',
  'Nestoria Rank':'',
  'Price (low to high)':'',
  'Price (high to low)':'',
  'Beds (fewer first)':'',
  'Beds (more first)':'',
  'Date (older first)':'',
  'Date (newer first)':'',
  'Bedrooms':'',
  'Price':'',
  'Property type':'',
  'all':'',
  'flat':'',
  'house':'',
  'Bathrooms':'',
  'Filters':'',
  '£':'',
};
