export const LANG_ES_NAME = 'es';

export const LANG_ES_TRANS = {
  'Map':'Mapa',
  'Faves':'Favoritos',
  'Search':'Buscar',
  'Home':'Casa',
  'To Rent':'Alquilar',
  'For Sale':'En venta',
  'Nestoria Rank':'Nestoria Rango',
  'Price (low to high)':'Precio (bajo a alto)',
  'Price (high to low)':'Precio (mayor a menor)',
  'Beds (fewer first)':'Camas (menos primero)',
  'Beds (more first)':'Camas (más primero)',
  'Date (older first)':'Fecha (más antigua primero)',
  'Date (newer first)':'Fecha (más reciente primero)',
  'Bedrooms':'Habitaciones',
  'Price':'Precio',
  'Property type':'Tipo de propiedad',
  'all':'todas',
  'flat':'plano',
  'house':'casa',
  'Bathrooms':'Baños',
  'Filters':'Filtros',
  '£':'€',
};
